In [133]:
from pymongo import MongoClient
import pandas as pd
from newspaper import Article
import numpy as np

In [134]:
client = MongoClient("localhost", 27017)

In [135]:
db = client["NewsDatabase"]
collection = db["Articles"]

In [136]:
df = pd.DataFrame()

for doc in collection.find():
    for key in doc.keys():
        if(key =="_id"):
            continue
        f = pd.DataFrame(doc[key])
        df = pd.concat([df,f],ignore_index=True)

In [137]:
df

title  \
0     Chief Minister does not trust government hospi...   
1     ₹18.23 lakh crore set as NTR district’s GDP ta...   
2     Watch: Uddhav-Raj joint rally, PM Modi in Arge...   
3     Yoga to be part of curriculum in RGUHS-affilia...   
4     This year, 1,51,436 engineering seats availabl...   
...                                                 ...   
999   Why physicists think geometry is the path to a...   
1000  Mice with two fathers have their own offspring...   
1001  Vera Rubin Observatory has already found thous...   
1002     Orcas scrub each other clean with bits of kelp   
1003  Stellar flares may hamper search for life in p...   

                                                   link  \
0     https://www.thehindu.com/news/national/kerala/...   
1     https://www.thehindu.com/news/national/andhra-...   
2     https://www.thehindu.com/videos/watch-uddhav-r...   
3     https://www.thehindu.com/news/national/karnata...   
4     https://www.thehindu.com/news/national/karnata...   
...                                                 ...   
999   https://www.newscientist.com/article/2484119-w...   
1000  https://www.newscientist.com/article/2485396-m...   
1001  https://www.newscientist.com/article/2485526-v...   
1002  https://www.newscientist.com/article/2485501-o...   
1003  https://www.newscientist.com/article/2485408-s...   

                                                summary  \
0     BJP State chief accuses the Left government of...   
1                                                         
2     Here are the top headlines in this edition of ...   
3                                                         
4                                                         
...                                                 ...   
999   From four-dimensional hexagons to the mind-ben...   
1000  We're a step closer to two men being able to h...   
1001  In just 10 hours of observing the night sky, t...   
1002  Drone footage has captured killer whales break...   
1003  Astronomers have been trying to detect atmosph...   

                            published          source  
0     Sat, 05 Jul 2025 23:05:47 +0530           Hindu  
1     Sat, 05 Jul 2025 23:03:23 +0530           Hindu  
2     Sat, 05 Jul 2025 23:02:49 +0530           Hindu  
3     Sat, 05 Jul 2025 22:58:14 +0530           Hindu  
4     Sat, 05 Jul 2025 22:57:00 +0530           Hindu  
...                               ...             ...  
999   Mon, 23 Jun 2025 15:00:36 +0100  News Scientist  
1000  Mon, 23 Jun 2025 21:00:04 +0100  News Scientist  
1001  Mon, 23 Jun 2025 20:46:51 +0100  News Scientist  
1002  Mon, 23 Jun 2025 17:00:43 +0100  News Scientist  
1003  Mon, 23 Jun 2025 15:00:53 +0100  News Scientist  

[1004 rows x 5 columns]

In [138]:
df_no_duplicates = df.drop_duplicates(subset="link",ignore_index=True)
df_no_duplicates

title  \
0    Chief Minister does not trust government hospi...   
1    ₹18.23 lakh crore set as NTR district’s GDP ta...   
2    Watch: Uddhav-Raj joint rally, PM Modi in Arge...   
3    Yoga to be part of curriculum in RGUHS-affilia...   
4    This year, 1,51,436 engineering seats availabl...   
..                                                 ...   
569  Transfer rumors, news: Barcelona told price to...   
570  Defending champs England fall at first hurdle,...   
571  Euro 2025 Daily: Wales fans light up Lucerne o...   
572  Can a microbe in soil alter your brain chemist...   
573  Fig trees may benefit climate by turning carbo...   

                                                  link  \
0    https://www.thehindu.com/news/national/kerala/...   
1    https://www.thehindu.com/news/national/andhra-...   
2    https://www.thehindu.com/videos/watch-uddhav-r...   
3    https://www.thehindu.com/news/national/karnata...   
4    https://www.thehindu.com/news/national/karnata...   
..                                                 ...   
569  https://www.espn.in/football/story/_/id/456748...   
570  https://www.espn.in/football/story/_/id/456792...   
571  https://www.espn.in/football/story/_/id/456757...   
572  https://www.newscientist.com/article/mg2663550...   
573  https://www.newscientist.com/article/2487119-f...   

                                               summary  \
0    BJP State chief accuses the Left government of...   
1                                                        
2    Here are the top headlines in this edition of ...   
3                                                        
4                                                        
..                                                 ...   
569  Barcelona have been told what they will need t...   
570  England's bid to defend their Euros title took...   
571  Wales fans celebrated as they made their tourn...   
572  Many claims are being made about Mycobacterium...   
573  Some carbon dioxide absorbed by fig trees gets...   

                           published          source  
0    Sat, 05 Jul 2025 23:05:47 +0530           Hindu  
1    Sat, 05 Jul 2025 23:03:23 +0530           Hindu  
2    Sat, 05 Jul 2025 23:02:49 +0530           Hindu  
3    Sat, 05 Jul 2025 22:58:14 +0530           Hindu  
4    Sat, 05 Jul 2025 22:57:00 +0530           Hindu  
..                               ...             ...  
569     Sun, 6 Jul 2025 14:55:49 EST     ESPN Sports  
570     Sun, 6 Jul 2025 17:22:31 EST     ESPN Sports  
571     Sun, 6 Jul 2025 17:22:32 EST     ESPN Sports  
572  Wed, 02 Jul 2025 19:00:00 +0100  News Scientist  
573  Sun, 06 Jul 2025 01:01:42 +0100  News Scientist  

[574 rows x 5 columns]

In [139]:
papers = []

In [140]:
for idx, row in df_no_duplicates.iterrows():
    article = Article(row["link"])
    article.download()
    article.parse()
    papers.append({"Title": row["title"], "Link": row["link"], "News":article.text})

In [141]:
new_df = pd.DataFrame(papers)
new_df

Title  \
0    Chief Minister does not trust government hospi...   
1    ₹18.23 lakh crore set as NTR district’s GDP ta...   
2    Watch: Uddhav-Raj joint rally, PM Modi in Arge...   
3    Yoga to be part of curriculum in RGUHS-affilia...   
4    This year, 1,51,436 engineering seats availabl...   
..                                                 ...   
569  Transfer rumors, news: Barcelona told price to...   
570  Defending champs England fall at first hurdle,...   
571  Euro 2025 Daily: Wales fans light up Lucerne o...   
572  Can a microbe in soil alter your brain chemist...   
573  Fig trees may benefit climate by turning carbo...   

                                                  Link  \
0    https://www.thehindu.com/news/national/kerala/...   
1    https://www.thehindu.com/news/national/andhra-...   
2    https://www.thehindu.com/videos/watch-uddhav-r...   
3    https://www.thehindu.com/news/national/karnata...   
4    https://www.thehindu.com/news/national/karnata...   
..                                                 ...   
569  https://www.espn.in/football/story/_/id/456748...   
570  https://www.espn.in/football/story/_/id/456792...   
571  https://www.espn.in/football/story/_/id/456757...   
572  https://www.newscientist.com/article/mg2663550...   
573  https://www.newscientist.com/article/2487119-f...   

                                                  News  
0    Bharatiya Janata Party (BJP) State president R...  
1    The administration has set a target of reachin...  
2    From Uddhav-Raj Thackeray joint rally to Trump...  
3    The Rajiv Gandhi University of Health Sciences...  
4    The Higher Education Department (Technical Edu...  
..                                                 ...  
569  Alexis Nunes and Frank Leboeuf react to Gonzal...  
570  Samuel Marsden and the ESPN FC crew discuss wh...  
571  Open Extended Reactions\n\nThe 2025 Women's Eu...  
572  Many claims are being made about Mycobacterium...  
573  Some carbon dioxide absorbed by fig trees gets...  

[574 rows x 3 columns]

In [142]:
collection = db["FullArticles"]
collection.insert_one({'Full Papers':papers})

InsertOneResult(ObjectId('688893ee0c4033505cbe7416'), acknowledged=True)

In [143]:
db = client["NewsDatabase"]
collection = db["FullArticles"]

In [144]:
last_doc = collection.find()
df = pd.DataFrame()
for doc in last_doc:
    articles_list = doc.get("Full Papers", [])
    f = pd.DataFrame(articles_list)
    df = pd.concat([df,f],ignore_index=True)
df

Title  \
0    Chief Minister does not trust government hospi...   
1    ₹18.23 lakh crore set as NTR district’s GDP ta...   
2    Watch: Uddhav-Raj joint rally, PM Modi in Arge...   
3    Yoga to be part of curriculum in RGUHS-affilia...   
4    This year, 1,51,436 engineering seats availabl...   
..                                                 ...   
569  Transfer rumors, news: Barcelona told price to...   
570  Defending champs England fall at first hurdle,...   
571  Euro 2025 Daily: Wales fans light up Lucerne o...   
572  Can a microbe in soil alter your brain chemist...   
573  Fig trees may benefit climate by turning carbo...   

                                                  Link  \
0    https://www.thehindu.com/news/national/kerala/...   
1    https://www.thehindu.com/news/national/andhra-...   
2    https://www.thehindu.com/videos/watch-uddhav-r...   
3    https://www.thehindu.com/news/national/karnata...   
4    https://www.thehindu.com/news/national/karnata...   
..                                                 ...   
569  https://www.espn.in/football/story/_/id/456748...   
570  https://www.espn.in/football/story/_/id/456792...   
571  https://www.espn.in/football/story/_/id/456757...   
572  https://www.newscientist.com/article/mg2663550...   
573  https://www.newscientist.com/article/2487119-f...   

                                                  News  
0    Bharatiya Janata Party (BJP) State president R...  
1    The administration has set a target of reachin...  
2    From Uddhav-Raj Thackeray joint rally to Trump...  
3    The Rajiv Gandhi University of Health Sciences...  
4    The Higher Education Department (Technical Edu...  
..                                                 ...  
569  Alexis Nunes and Frank Leboeuf react to Gonzal...  
570  Samuel Marsden and the ESPN FC crew discuss wh...  
571  Open Extended Reactions\n\nThe 2025 Women's Eu...  
572  Many claims are being made about Mycobacterium...  
573  Some carbon dioxide absorbed by fig trees gets...  

[574 rows x 3 columns]

In [145]:
data = pd.Series(df["News"])
data

0      Bharatiya Janata Party (BJP) State president R...
1      The administration has set a target of reachin...
2      From Uddhav-Raj Thackeray joint rally to Trump...
3      The Rajiv Gandhi University of Health Sciences...
4      The Higher Education Department (Technical Edu...
                             ...                        
569    Alexis Nunes and Frank Leboeuf react to Gonzal...
570    Samuel Marsden and the ESPN FC crew discuss wh...
571    Open Extended Reactions\n\nThe 2025 Women's Eu...
572    Many claims are being made about Mycobacterium...
573    Some carbon dioxide absorbed by fig trees gets...
Name: News, Length: 574, dtype: object

In [146]:
import re
import string
from nltk.stem import PorterStemmer

for i,art in enumerate(df["News"]):
    text_no_punct = art.translate(str.maketrans('', '', string.punctuation))
    text_no_numbers = re.sub(r'\d+', '', text_no_punct)
    words = text_no_numbers.split()
    stemmer = PorterStemmer()
    stemmed_words = [stemmer.stem(word) for word in words]
    data[i] = ' '.join(stemmed_words)

In [147]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(stop_words='english')
X = vectorizer.fit_transform(data)
print(vectorizer.get_feature_names_out())
print(X.toarray())

['aadhaar' 'aadhar' 'aadmi' ... 'željko' 'ζdepend' 'filed']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [148]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_matrix = cosine_similarity(X)

In [149]:
print(similarity_matrix)

[[1.         0.10256785 0.         ... 0.04742768 0.05311607 0.02172255]
 [0.10256785 1.         0.02482605 ... 0.09404807 0.09278897 0.03479163]
 [0.         0.02482605 1.         ... 0.07174775 0.09183205 0.0485339 ]
 ...
 [0.04742768 0.09404807 0.07174775 ... 1.         0.19858472 0.07660836]
 [0.05311607 0.09278897 0.09183205 ... 0.19858472 1.         0.15198258]
 [0.02172255 0.03479163 0.0485339  ... 0.07660836 0.15198258 1.        ]]


In [156]:
collection = db["User"]
source = collection.find_one({"likedArticles":{"$exists": True}})
likedArticles = source.get("likedArticles")

In [178]:
source = collection.find_one({"dislikedArticles":{"$exists": True}})
dislikedArticles = source.get("dislikedArticles")

In [179]:
likedIndexes = new_df[new_df["Link"].isin(likedArticles)].index
dislikedIndexes = new_df[new_df["Link"].isin(dislikedArticles)].index

In [180]:
user_profile = X[likedIndexes].mean(axis=0) - X[dislikedIndexes].mean(axis=0)
user_profile

matrix([[0., 0., 0., ..., 0., 0., 0.]])

In [181]:
similarities = cosine_similarity(np.array(user_profile), X.toarray()).flatten()

for idx in likedIndexes:
    similarities[idx] = -1

top_indices = similarities.argsort()[::-1][:10]
top_indices_scores = similarities[similarities.argsort()[::-1][:10]]
print("Recommended articles:", top_indices)
print("scores",top_indices_scores)


Recommended articles: [413 568 447 301 561 282 306 366 293 337]
scores [0.16187674 0.1438528  0.13961232 0.13877081 0.11796503 0.11280194
 0.10656861 0.10571695 0.10556047 0.10501857]


In [187]:
for k,i in enumerate(likedIndexes):
    print(k+1, df.iloc[i]["Title"])

1 IISc to study feasibility of Hemavati river link canal project
2 Book on antiquity of Telugu language launched at TANA conference
3 High-quality diet may have led to bigger human brain: CSIR-CCMB-led international study reveals genetic link between diet and brain size
4 Online access to citizens for GHMC property tax services
5 Hyderabad man arrested for pirating 40 movies
6 LIVE: Day four awaits in Edgbaston
7 Gill breaks records with 430 as India rack up a rare 1000
8 July 4: Gukesh opens three-point lead at Croatia Grand Chess Tour
9 FIDE Women's Chess World Cup 2025: Humpy leads Indian charge at 107-strong field with an eye on Candidates
10 FIDE Chess rankings for July: R Praggnanandhaa becomes India no.1 in classical
11 New IQ research shows why smarter people make better decisions
12 New research confirms that neurons form in the adult brain
13 AI spots deadly heart risk most doctors can't see
14 This AI tracks lung tumors as you breathe — and it might save lives
15 Quantum com

In [189]:
for k,i in enumerate(top_indices):
    print(k+1, df.iloc[i]["Title"])

1 The best new science fiction books of July 2025
2 Gukesh, Pragg in Croatia GCT blitz final round; Women's Chess World Cup begins, Skeet shooters in Logano World Cup: Indian Sports LIVE, July 6
3 Spiders that get eaten after sex are picky about mates. You don't say
4 New year, New Pragg: How a change in mentality pushed Praggnanandhaa past Gukesh as India's new no.1
5 Dortmund coach: MetLife field more suited to golf
6 Srikanth stuns top seed Chen to enter Canada Open SF; Gukesh leads before Croatia GCT blitz; Neeraj Chopra Classic: Indian Sports LIVE, July 5
7 Ayush Shetty enters the big leagues with drought ending BWF World Tour title
8 Brain scan breakthrough reveals why Parkinson’s drugs don’t always work
9 NBA free agency winners and losers: Early results are in
10 A midlife MRI that spots rapid aging and signals disease long before symptoms


In [190]:
client.close()